<img style="float: left;;" src='Figures/alinco.png' height="100"/></a>

# <center> <font color= #000047> NumPy Indexación y selección</font> </center>




En este apartado veremos como seleccionar elementos o grupos de elementos de un arreglo.

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Selección e indexación mediante Brackets
La forma más sencilla de elegir uno o algunos elementos de un arreglo es muy similar a las listas de Python:

In [3]:
arr[8]

8

In [4]:
arr[1:5]

array([1, 2, 3, 4])

In [5]:
arr[6:9]

array([6, 7, 8])

In [7]:
arr[6:13]

array([ 6,  7,  8,  9, 10])

## Broadcasting

Los arreglos en NumPy se diferencian de las listas normales de Python debido a su capacidad para reasignar valores. Con las listas, solo puede reasignar partes de una lista con partes nuevas del mismo tamaño y forma. Es decir, si quisiera reemplazar los primeros 5 elementos de una lista con un nuevo valor, tendría que pasar una nueva lista de 5 elementos. Con los arreglos de NumPy, podemos reasignar un solo valor a través de un conjunto más grande de valores:


In [8]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [10]:
arr2 = np.arange(0,11)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Los datos no se copian, sólo es un pedazo del arreglo original.

In [11]:
slice_arr = arr2[0:6]
slice_arr

array([0, 1, 2, 3, 4, 5])

In [12]:
slice_arr[:]=99
slice_arr

array([99, 99, 99, 99, 99, 99])

In [13]:
slice_arr[:]=99
slice_arr

array([99, 99, 99, 99, 99, 99])

In [14]:
arr2

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [15]:
arr_copy = arr.copy()
arr_copy

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [16]:
arr_copy[0:5]=10
arr_copy

array([10, 10, 10, 10, 10,  5,  6,  7,  8,  9, 10])

In [17]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

## Indexación de un arreglo 2D (matrices)

Lo forma general es: **arr_2d[row][col]** o **arr_2d[row,col]**.

In [18]:
arr_2d = np.array([[5,10,15],
                  [20,25,30],
                  [35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [19]:
arr_2d[1][1]

25

In [20]:
arr_2d[1,1]

25

In [21]:
arr_2d[0]

array([ 5, 10, 15])

In [24]:
arr_2d[0:2,0:2]

array([[ 5, 10],
       [20, 25]])

In [25]:
arr_2d[:2,:2]

array([[ 5, 10],
       [20, 25]])

In [27]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [26]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

## Más sobre indexación
Indexar una matriz 2D puede ser un poco confuso al principio, especialmente cuando se tiene un mator tamaño en la matriz.

Una imagen útil para entender el concepto de indexación:

<img src= 'Figures/numpy_indexing.png' width=500/> 

In [28]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : integer or real, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : integer or real
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off 

In [33]:
a = np.arange(36).reshape(6,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

## Selección Condicional

Este es un concepto muy fundamental que nos servirá en la librería de Pandas más adelante, ¡asegúrate de entender esta parte!


In [34]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [36]:
bool_arr = arr>4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [39]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [38]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
arr==2

array([False,  True, False, False, False, False, False, False, False,
       False])

In [41]:
arr[arr==2]

array([2])

In [44]:
a_l = arr > 2 
a_l

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [45]:
a_l2 = arr <=5
a_l2

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [46]:
a_log = a_l & a_l2
a_log

array([False, False,  True,  True,  True, False, False, False, False,
       False])

In [47]:
arr[a_log]

array([3, 4, 5])

In [49]:
arr>2 & arr<=5

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()