
<img style="float: left;;" src='Figures/alinco.png' height="100"/></a>

# <center> <font color= #000047>  Operaciones con NumPy</font> </center>



## Aritméticas

Podemos realizar fácilmente aritmeticas como *arreglo con arreglo* , o *escalar con arreglo*. Veamos algunos ejemplos: 

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [8]:
arr2 = arr.reshape(10,1)
arr2

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [10]:
arr = arr.reshape(1,10)
arr

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [11]:
arr.shape

(1, 10)

In [12]:
arr2.shape

(10, 1)

In [13]:
np.dot(arr,arr2)

array([[285]])

In [14]:
np.matmul(arr,arr2)

array([[285]])

In [16]:
arr@arr2

array([[285]])

In [17]:
lista_1 = [1,2,3,4]

In [18]:
lista_1 + lista_1

[1, 2, 3, 4, 1, 2, 3, 4]

In [19]:
# Crear una matriz aleatoria de números enteros de dimensión 4x2 -> A
# Crear una matriz aleatoria de números enteros de dimensión 2x6 -> B
# Realizar la multiplicación de Matrices C = A*B
# Realizar la multiplicación de Matrices C = B*A

A = np.random.randint(100,size=(4,2))
B = np.random.randint(100, size=(2,6))

In [20]:
C = A@B
C

array([[ 3586,  3765, 10162,  6996,  7324,  5600],
       [ 3122,  3325,  9394,  6692,  6748,  5600],
       [ 1038,  1203,  4254,  3468,  3012,  3360],
       [ 4646,  4791, 12158,  7956,  8804,  5920]])

In [21]:
C = np.dot(A,B)
C

array([[ 3586,  3765, 10162,  6996,  7324,  5600],
       [ 3122,  3325,  9394,  6692,  6748,  5600],
       [ 1038,  1203,  4254,  3468,  3012,  3360],
       [ 4646,  4791, 12158,  7956,  8804,  5920]])

In [22]:
A.shape

(4, 2)

In [23]:
B.shape

(2, 6)

In [24]:
B@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 6)

## Funciones universales en los Arreglos

NumPy viene con muchass [funciones universales en los arreglos](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), or <em>ufuncs</em>, que son esencialmente operaciones matemáticas que se pueden aplicar al arreglo.<br>Veamos algunas funciones más comunes:

In [25]:
arr

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [26]:
np.sqrt(arr)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
        2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ]])

In [27]:
np.exp(arr)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
        2.98095799e+03, 8.10308393e+03]])

In [28]:
np.sin(arr)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
        -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849]])

In [29]:
np.cos(arr)

array([[ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
         0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026]])

In [30]:
arr.transpose()

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [31]:
arr.T

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

## Resumen de Estadística sobre Arreglos

NumPy también ofrece métodos estadísticos como <em> sum </em>, <em> mean </em> y <em> max </em>. 

In [32]:
arr.sum()

45

In [33]:
arr.var()

8.25

In [34]:
arr.std()

2.8722813232690143

In [35]:
arr.max()

9

## Lógica para el eje (axis)

Cuando trabajamos con arreglos bidimensionales, debemos considerar filas y columnas. En términos de un arreglo, el eje 0 (cero) es el eje horizontal (filas) y el eje 1 es el eje vertical (columnas). Los valores (0,1) corresponden al orden en el que método <tt> arr.shape </tt> da como salida.

Veamos cómo afecta esto a nuestros cálculos estadísticos resumidos de arriba.


In [36]:
A

array([[57, 70],
       [49, 70],
       [15, 42],
       [75, 74]])

In [37]:
A.sum()

452

In [38]:
A.sum(axis=0)

array([196, 256])

In [39]:
A.sum(axis=1)

array([127, 119,  57, 149])

Dando como entrada <tt>axis=0</tt>, estamos devolviendo la suma del arreglo a lo largo del eje vertical, esencialmente <tt>[(1+5+9), (2+6+10), (3+7+11), (4+8+12)]</tt>

<img src='Figures/axis_logic.png' width=400/>

Esto nos dice que <tt>arr_2d</tt> tiene 3 filas y 4 columnas.

En <tt>arr_2d.sum(axis=0)</tt>, se sumó el primer elemento de cada fila, luego el segundo elemento y así sucesivamente.

Entonces, ¿qué debería <tt>arr_2d.sum(axis=1)</tt> regresar?

## Ejercicio 1


### Numpy

1. Crear un vector con valores de 10 a 69.
2. Elevar al cuadrado a aquellos números divisibles por 3.
3. Redimensionar ese vector en una matriz de 10x2.
4. Crear una nueva matriz de enteros 2x10 y multiplicarla a la matriz anterior.
5. Obtener la transpuesta de la matriz resultante.

In [43]:
a = np.arange(10,70)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69])

In [46]:
a2 = a[a%3 == 0]**2
a2

array([ 144,  225,  324,  441,  576,  729,  900, 1089, 1296, 1521, 1764,
       2025, 2304, 2601, 2916, 3249, 3600, 3969, 4356, 4761], dtype=int32)

In [47]:
a2.shape

(20,)

In [49]:
a2 = a2.reshape(10,2)
a2

array([[ 144,  225],
       [ 324,  441],
       [ 576,  729],
       [ 900, 1089],
       [1296, 1521],
       [1764, 2025],
       [2304, 2601],
       [2916, 3249],
       [3600, 3969],
       [4356, 4761]], dtype=int32)

In [50]:
b = np.random.randint(100,size=(2,10))
b

array([[19, 78, 73, 16, 58, 50, 88, 20, 28, 86],
       [77, 98, 80, 24, 61, 56, 80, 44, 48, 58]])

In [51]:
a2.shape


(10, 2)

In [52]:
b.shape

(2, 10)

In [54]:
C = a2@b
C

array([[ 20061,  33282,  28512,   7704,  22077,  19800,  30672,  12780,
         14832,  25434],
       [ 40113,  68490,  58932,  15768,  45693,  40896,  63792,  25884,
         30240,  53442],
       [ 67077, 116370, 100368,  26712,  77877,  69624, 109008,  43596,
         51120,  91818],
       [100953, 176922, 152820,  40536, 118629, 105984, 166320,  65916,
         77472, 140562],
       [141741, 250146, 216288,  57240, 167949, 149976, 235728,  92844,
        109296, 199674],
       [189441, 336042, 290772,  76824, 225837, 201600, 317232, 124380,
        146592, 269154],
       [244053, 434610, 376272,  99288, 292293, 260856, 410832, 160524,
        189360, 349002],
       [305577, 545850, 472788, 124632, 367317, 327744, 516528, 201276,
        237600, 439218],
       [374013, 669762, 580320, 152856, 450909, 402264, 634320, 246636,
        291312, 539802],
       [449361, 806346, 698868, 183960, 543069, 484416, 764208, 296604,
        350496, 650754]])

In [55]:
C.T

array([[ 20061,  40113,  67077, 100953, 141741, 189441, 244053, 305577,
        374013, 449361],
       [ 33282,  68490, 116370, 176922, 250146, 336042, 434610, 545850,
        669762, 806346],
       [ 28512,  58932, 100368, 152820, 216288, 290772, 376272, 472788,
        580320, 698868],
       [  7704,  15768,  26712,  40536,  57240,  76824,  99288, 124632,
        152856, 183960],
       [ 22077,  45693,  77877, 118629, 167949, 225837, 292293, 367317,
        450909, 543069],
       [ 19800,  40896,  69624, 105984, 149976, 201600, 260856, 327744,
        402264, 484416],
       [ 30672,  63792, 109008, 166320, 235728, 317232, 410832, 516528,
        634320, 764208],
       [ 12780,  25884,  43596,  65916,  92844, 124380, 160524, 201276,
        246636, 296604],
       [ 14832,  30240,  51120,  77472, 109296, 146592, 189360, 237600,
        291312, 350496],
       [ 25434,  53442,  91818, 140562, 199674, 269154, 349002, 439218,
        539802, 650754]])

## Ejercicio 2

Se desea calcular el índice de masa corporal (IMC) de jugadores de un equipo de futbol. Los datos proporcionados corresponden a las listas de los nombres, altura y peso, tal como se muestra a continuación

In [ ]:
nombre= ['Bonifacio de Cifuentes',
'Ángel Machado Lara',
'Geraldo de Atienza',
'Onofre Posada Grande',
'Samu Cantón-Figuerola',
'Camilo Pol',
'Toni Galvez Lara',
'Lucho Manzano Rivas',
'Abraham Aroca',
'Anselmo Bartolomé Folch',
'Toni Inocencio Rozas Porras',
'Fausto Cortés-Arco',
'Baltasar Carreño Isern']

altura = [180, 215, 210, 210, 188, 176, 209, 200, 210, 188, 176, 209, 200]
peso = [69, 74, 72, 75, 68, 70, 71, 73, 69, 74, 72, 75, 68, 70, 71, 73]

El valor de IMC por cada jugador resulta de aplicar la fórmula:

$$IMC = \frac{peso(kg)}{altura(m)^2}$$

**Nota:** Los valores de altura están dados en centímetros por lo que deberá hacer laconversión a metros previo a la aplicación de la fórmula. Adicionalmente, una vez obtenido el IMC se solicita:

> a) Presentar el icm para cada jugador.

> b) Indicar en qué índice se encuentra el icm más alto y a qué jugador le pertenece.

> c) Calcular el promedio de los icm resultantes.

> d) Muestre los nombres de los jugadores en orden de su imc, desde el que tiene menorimc al que tiene mayor imc.