<img style="float: left;;" src='Figures/alinco.png'/></a>

# <center> <font color= #000047> Ejercicios Numpy 




<img style="float: right; margin: 0px 0px 15px 15px;" src="https://upload.wikimedia.org/wikipedia/commons/1/1a/NumPy_logo.svg" width="400px" height="400px" />



¿Recuerdan algo de álgebra lineal? Por ejemplo:
- vectores;
- suma de vectores;
- producto por un escalar ...

¿Cómo se les ocurre que podríamos manejar lo anterior en Python?

In [1]:
# Crear dos vectores
x = [4,5,8,-2,3]
y = [3,1,-7,-9,5]


In [2]:
x, y

([4, 5, 8, -2, 3], [3, 1, -7, -9, 5])

In [3]:
# Suma de vectores
x+y

[4, 5, 8, -2, 3, 3, 1, -7, -9, 5]

In [7]:
# ¿con ciclos quizá?
sum_ = [x[i] + y[i] for i in range(len(x))]
sum_

[7, 6, 1, -11, 8]

In [5]:
# Producto por escalar
3*x

[4, 5, 8, -2, 3, 4, 5, 8, -2, 3, 4, 5, 8, -2, 3]

In [6]:
# ¿con ciclos quizá?
prod_ = [x[i] * y[i] for i in range(len(x))]
prod_

[12, 5, -56, 18, 15]

### Solución: NumPy

NumPy es la librería fundamental para computación científica con Python. Contiene, entre otros:
- una clase de objetos tipo arreglo N-dimensional muy poderso;
- funciones matemáticas sofisticadas;
- herramientas matemáticas útiles de álgebra lineal, transformada de Fourier y números aleatorios.

Aparte de sus usos científicos, NumPy puede ser usada como un contenedor eficiente de datos multidimensional, lo que le otorga a NumPy una capacidad impresionante de integración con bases de datos.

Por otra parte, casi todas las librerías de Python relacionadas con ciencia de datos y machine learning tales como SciPy (Scientific Python), Mat-plotlib (librería de gráficos), Scikit-learn, dependen de NumPy razonablemente.

Para nuestra fortuna, NumPy ya viene instalado por defecto en la instalación de Anaconda.

Así que si queremos empezar a utilizarlo, lo único que debemos hacer es importarlo:

In [8]:
# Importar numpy
import numpy as np

Lo que acabamos de hacer es un procedimiento genérico para importar librerías:
- se comienza con la palabra clave `import`;
- a continuación el nombre de la librería, en este caso `numpy`;
- opcionalmente se puede incluir una cláusula `as` y una abreviación del nombre de la librería. Para el caso de NumPy, la comunidad comúmente usa la abreviación `np`.

Ahora, intentemos hacer lo mismo que que antes, pero con el arreglo n-dimensional que provee NumPy como vector:

In [ ]:
# Ayuda sobre arreglo N-dimensional


In [ ]:
# Crear dos vectores


In [ ]:
# Suma de vectores


In [ ]:
# Producto interno


### Diferencias fundamentales entre Listas de Python y Arreglos de NumPy

Mientras que las listas y los arreglos tienen algunas similaridades (ambos son colecciones ordenadas de valores), existen ciertas diferencias abismales entre este tipo de estructuras de datos:

- A diferencia de las listas, todos los elementos en un arreglo de NumPy deben ser del mismo tipo de datos (esto es, todos enteros, o flotantes, o strings, etc).

- Por lo anterior, los arreglos de NumPy soportan operaciones aritméticas y otras funciones matemáticas que se ejecutan en cada elemento del arreglo. Las listas no soportan estos cálculos.

- Los arreglos de NumPy tienen dimensionalidad.

## 1.1 Funciones de NumPy

### Problema 1

> Dados cinco (5) contenedores cilíndricos con diferentes radios y alturas que pueden variar entre 5 y 25 cm, encontrar:
> 1. El volumen del agua que puede almacenar cada contenedor;
> 2. El volumen total del agua que pueden almacenar todos los contenedores juntos;
> 3. Cual contenedor puede almacenar más volumen, y cuanto;
> 4. Cual contenedor puede almacenar menos volumen, y cuanto;
> 5. Obtener la media, la mediana y la desviación estándar de los volúmenes de agua que pueden ser almacenados en los contenedores.

Antes que nada, definamos las variables que nos dan:

In [9]:
# Definir numero de contenedores, medida minima y medida maxima
n_contenedores = 5
medida_min = 5
medida_max = 25

A continuación, generaremos un arreglo de números enteros aleatorios entre 5 y 25 cm que representarán los radios y las alturas de los cilindros:

In [10]:
# Ayuda de np.random.randint()
np.random.seed(10)
medidas = np.random.randint(medida_min,medida_max,size=(10,))
medidas

array([14,  9, 20,  5, 22, 21, 22, 13, 14,  5])

In [11]:
# array.reshape
medidas = medidas.reshape((2,5))
medidas

array([[14,  9, 20,  5, 22],
       [21, 22, 13, 14,  5]])

De los números generados, separemos los que corresponden a los radios, y los que corresponden a las alturas:

In [12]:
# Radios
radios = medidas[0,:]
radios

array([14,  9, 20,  5, 22])

In [13]:
# Alturas
alturas = medidas[1,:]
alturas

array([21, 22, 13, 14,  5])

1. Con lo anterior, calculemos cada uno los volúmenes:

In [15]:
volumenes = (np.pi*radios**2)*alturas
volumenes

array([12930.79536218,  5598.3181087 , 16336.28179867,  1099.55742876,
        7602.65422169])

<img style="float: right; margin: 0px 0px 15px 15px;" src="https://upload.wikimedia.org/wikipedia/commons/b/b3/Symbol_great.svg" width="400px" height="400px" />

### ¡Excelente!

Con esta línea de código tan sencilla, pudimos obtener de un solo jalón todos los volúmenes de nuestros contenedores.

Esta es la potencia que nos ofrece NumPy. Podemos operar los arreglos de forma rápida, sencilla, y muy eficiente.

2. Ahora, el volumen total

In [16]:
# Volumen total
volumenes.sum()

43567.60691998326

3. ¿Cuál contenedor puede almacenar más volumen? ¿Cuánto?

In [17]:
volumenes

array([12930.79536218,  5598.3181087 , 16336.28179867,  1099.55742876,
        7602.65422169])

In [18]:
# Contenedor que puede almacenar más volumen
volumenes.argmax()

2

In [19]:
# Volumen máximo
volumenes.max()

16336.281798666925

In [20]:
# También se puede, pero no es recomendable. Ver comparación de tiempos
max(volumenes)

16336.281798666925

In [21]:
random_vector = np.random.randint(0,100,size=(1000,))

In [22]:
%timeit random_vector.max()

3.15 µs ± 228 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [23]:
%timeit max(random_vector)

50.3 µs ± 5.29 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


4. ¿Cuál contenedor puede almacenar menos volumen? ¿Cuánto?

In [24]:
# Contenedor que puede almacenar menos volumen
volumenes.argmin()

3

In [25]:
# Volumen mínimo
volumenes.min()

1099.5574287564277

5. Media, mediana y desviación estándar de los volúmenes

In [26]:
# Media, mediana y desviación estándar
volumenes.mean(), volumenes.std()

(8713.521383996651, 5381.502402803914)

In [ ]:
# Atributos shape y dtype


## 1.2 Trabajando con matrices

### Problema 2

> 25 cartas numeradas de la 1 a la 25 se distribuyen aleatoriamente y en partes iguales a 5 personas. Encuentre la suma de cartas para cada persona tal que: 
> - para la primera persona, la suma es el valor de la primera carta menos la suma del resto de las cartas;
> - para la segunda persona, la suma es el valor de la segunda carta menos la suma del resto de las cartas;
> - y así sucesivamente ...

> La persona para la cual la suma sea mayor, será el ganador. Encontrar el ganador.

Lo primero será generar los números del 1 al 25. ¿Cómo podemos hacer esto?

np.arange = np.array(range)

In [ ]:
# Ayuda en la función np.arange()


In [27]:
# Números del 1 al 25
cartas = np.arange(1,26)
cartas

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

Luego, tal y como en un juego de cartas, deberíamos barajarlos, antes de repartirlos:

In [28]:
# Ayuda en la función np.random.shuffle()
help(np.random.shuffle)

Help on built-in function shuffle:

shuffle(...) method of numpy.random.mtrand.RandomState instance
    shuffle(x)
    
    Modify a sequence in-place by shuffling its contents.
    
    This function only shuffles the array along the first axis of a
    multi-dimensional array. The order of sub-arrays is changed but
    their contents remains the same.
    
    .. note::
        New code should use the ``shuffle`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    x : ndarray or MutableSequence
        The array, list or mutable sequence to be shuffled.
    
    Returns
    -------
    None
    
    See Also
    --------
    Generator.shuffle: which should be used for new code.
    
    Examples
    --------
    >>> arr = np.arange(10)
    >>> np.random.shuffle(arr)
    >>> arr
    [1 7 5 2 9 4 3 6 0 8] # random
    
    Multi-dimensional arrays are only shuffled along the first axis:
    
    >>> ar

In [29]:
# Barajar
np.random.shuffle(cartas)

In [30]:
# Ver valores
cartas

array([19,  8, 17,  9, 14,  3,  7, 15,  1, 18, 21, 22,  4, 25, 12, 20,  2,
       23, 16, 10, 11,  5, 24, 13,  6])

Bien. Ahora, deberíamos distribuir las cartas. Podemos imaginarnos la distribución como una matriz 5x5:

In [31]:
# Repartir cartas
cartas=cartas.reshape((5,5))
cartas

array([[19,  8, 17,  9, 14],
       [ 3,  7, 15,  1, 18],
       [21, 22,  4, 25, 12],
       [20,  2, 23, 16, 10],
       [11,  5, 24, 13,  6]])

In [ ]:
# Ver valores


Entonces, tenemos 5 cartas para cada una de las 5 personas, visualizadas como una matriz 5x5.

Lo único que nos falta es encontrar la suma para cada uno, es decir, sumar el elemento de la diagonal principal y restar las demás entradas de la fila (o columna).

¿Cómo hacemos esto?

In [33]:
# Ayuda en la función np.eye()
I5 = np.eye(5)
I5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
# Matriz con la diagonal principal
I5*cartas

array([[19.,  0.,  0.,  0.,  0.],
       [ 0.,  7.,  0.,  0.,  0.],
       [ 0.,  0.,  4.,  0.,  0.],
       [ 0.,  0.,  0., 16.,  0.],
       [ 0.,  0.,  0.,  0.,  6.]])

In [35]:
# Ayuda en la función np.ones()
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C', *, like=None)
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
    
        .. note::
            

In [37]:
# Matriz con los elementos fuera de la diagonal negativos
complemento = np.ones((5,5)) - I5
complemento

array([[0., 1., 1., 1., 1.],
       [1., 0., 1., 1., 1.],
       [1., 1., 0., 1., 1.],
       [1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 0.]])

In [38]:
# Matriz completa
cartas*complemento

array([[ 0.,  8., 17.,  9., 14.],
       [ 3.,  0., 15.,  1., 18.],
       [21., 22.,  0., 25., 12.],
       [20.,  2., 23.,  0., 10.],
       [11.,  5., 24., 13.,  0.]])

In [39]:
Matriz_para_suma = I5*cartas - complemento*cartas
Matriz_para_suma

array([[ 19.,  -8., -17.,  -9., -14.],
       [ -3.,   7., -15.,  -1., -18.],
       [-21., -22.,   4., -25., -12.],
       [-20.,  -2., -23.,  16., -10.],
       [-11.,  -5., -24., -13.,   6.]])

In [40]:
# Sumar por filas
suma = Matriz_para_suma.sum(axis=0)
suma

array([-36., -30., -75., -32., -48.])

¿Quién es el ganador?

In [41]:
suma.argmax()

1